version: '3'
services:
  frontend:
    build: .
    image: mixnjuice/frontend:latest
    container_name: mixnjuice-frontend
    restart: always
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - API_URL
    networks:
      - proxy_proxy
networks:
  proxy_proxy:
    external: true
