version: 2.1

jobs:
  build:
    working_directory: ~/gusta-frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest codecov'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: 'npm test && codecov'

workflows:
  version: 2
  main_workflow:
    jobs:
      - build:
          context: builds
